---
- hosts: web
  become: yes
  tasks:
  - name: deploy app binary
    copy:
      src: /home/ansible/apps/hello
      dest: /var/www/html/hello
    tags:
      - webdeploy

- hosts: db
  become: yes
  tasks:
  - name: deploy db script
    copy:
      src: /home/ansible/apps/script.sql
      dest: /opt/db/scripts/script.sql
    tags:
      - dbdeploy
